// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feed.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const deleteFeedByFetchFrom = `-- name: DeleteFeedByFetchFrom :exec
DELETE FROM feeds WHERE fetch_from = ?
`

func (q *Queries) DeleteFeedByFetchFrom(ctx context.Context, fetchFrom string) error {
	_, err := q.db.ExecContext(ctx, deleteFeedByFetchFrom, fetchFrom)
	return err
}

const deleteFeedByID = `-- name: DeleteFeedByID :exec
DELETE FROM feeds WHERE id = ?
`

func (q *Queries) DeleteFeedByID(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteFeedByID, id)
	return err
}

const getFeedByID = `-- name: GetFeedByID :one
SELECT id, title, description, link, fetch_from, language, ttl, etag, lastmodified FROM feeds WHERE id = ?
`

func (q *Queries) GetFeedByID(ctx context.Context, id int64) (Feed, error) {
	row := q.db.QueryRowContext(ctx, getFeedByID, id)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Link,
		&i.FetchFrom,
		&i.Language,
		&i.Ttl,
		&i.Etag,
		&i.Lastmodified,
	)
	return i, err
}

const upsertFeed = `-- name: UpsertFeed :one
INSERT INTO feeds(title, description, link, fetch_from, language, ttl, etag, lastModified)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?)
    ON CONFLICT(fetch_from) DO UPDATE
    SET title=excluded.title,
    description=excluded.description,
    link=excluded.link,
    fetch_from=excluded.fetch_from,
    language=excluded.language,
    ttl=excluded.ttl,
    etag=excluded.etag,
    lastModified=excluded.lastModified
    RETURNING id, title, description, link, fetch_from, language, ttl, etag, lastmodified
`

type UpsertFeedParams struct {
	Title        string
	Description  string
	Link         string
	FetchFrom    string
	Language     sql.NullString
	Ttl          int64
	Etag         sql.NullString
	Lastmodified time.Time
}

func (q *Queries) UpsertFeed(ctx context.Context, arg UpsertFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, upsertFeed,
		arg.Title,
		arg.Description,
		arg.Link,
		arg.FetchFrom,
		arg.Language,
		arg.Ttl,
		arg.Etag,
		arg.Lastmodified,
	)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Link,
		&i.FetchFrom,
		&i.Language,
		&i.Ttl,
		&i.Etag,
		&i.Lastmodified,
	)
	return i, err
}
