// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: item.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const deleteItemByID = `-- name: DeleteItemByID :exec
DELETE FROM items WHERE items.id = ?
`

func (q *Queries) DeleteItemByID(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteItemByID, id)
	return err
}

const deleteItemsOlderThan = `-- name: DeleteItemsOlderThan :exec
DELETE FROM items WHERE unixepoch() - unixepoch(items.pubDate) > unixepoch(?)
`

func (q *Queries) DeleteItemsOlderThan(ctx context.Context, unixepoch interface{}) error {
	_, err := q.db.ExecContext(ctx, deleteItemsOlderThan, unixepoch)
	return err
}

const getItemByGUID = `-- name: GetItemByGUID :one
SELECT id, feedid, guid, title, description, link, author, pubdate, read, starred FROM items WHERE items.guid = ?
`

func (q *Queries) GetItemByGUID(ctx context.Context, guid string) (Item, error) {
	row := q.db.QueryRowContext(ctx, getItemByGUID, guid)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Feedid,
		&i.Guid,
		&i.Title,
		&i.Description,
		&i.Link,
		&i.Author,
		&i.Pubdate,
		&i.Read,
		&i.Starred,
	)
	return i, err
}

const getItemByID = `-- name: GetItemByID :one
SELECT id, feedid, guid, title, description, link, author, pubdate, read, starred FROM items WHERE items.id = ?
`

func (q *Queries) GetItemByID(ctx context.Context, id int64) (Item, error) {
	row := q.db.QueryRowContext(ctx, getItemByID, id)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Feedid,
		&i.Guid,
		&i.Title,
		&i.Description,
		&i.Link,
		&i.Author,
		&i.Pubdate,
		&i.Read,
		&i.Starred,
	)
	return i, err
}

const getStarredItems = `-- name: GetStarredItems :many
SELECT id, feedid, guid, title, description, link, author, pubdate, read, starred FROM items WHERE items.starred = 1
`

func (q *Queries) GetStarredItems(ctx context.Context) ([]Item, error) {
	rows, err := q.db.QueryContext(ctx, getStarredItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.Feedid,
			&i.Guid,
			&i.Title,
			&i.Description,
			&i.Link,
			&i.Author,
			&i.Pubdate,
			&i.Read,
			&i.Starred,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnreadItems = `-- name: GetUnreadItems :many
SELECT id, feedid, guid, title, description, link, author, pubdate, read, starred FROM items WHERE items.read = 0
`

func (q *Queries) GetUnreadItems(ctx context.Context) ([]Item, error) {
	rows, err := q.db.QueryContext(ctx, getUnreadItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.Feedid,
			&i.Guid,
			&i.Title,
			&i.Description,
			&i.Link,
			&i.Author,
			&i.Pubdate,
			&i.Read,
			&i.Starred,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertItem = `-- name: UpsertItem :one
INSERT INTO items(guid, title, description, link, author, pubDate, read, starred)
    VALUES(?, ?, ?, ?, ?, ?, ?, ?)
    ON CONFLICT(id, guid) DO UPDATE
    SET guid=excluded.guid,
    title=excluded.title,
    description=excluded.description,
    link=excluded.link,
    author=excluded.author,
    pubDate=excluded.pubDate,
    read=excluded.read,
    starred=excluded.starred
    RETURNING id, feedid, guid, title, description, link, author, pubdate, read, starred
`

type UpsertItemParams struct {
	Guid        string
	Title       sql.NullString
	Description sql.NullString
	Link        sql.NullString
	Author      sql.NullString
	Pubdate     time.Time
	Read        sql.NullInt64
	Starred     sql.NullInt64
}

func (q *Queries) UpsertItem(ctx context.Context, arg UpsertItemParams) (Item, error) {
	row := q.db.QueryRowContext(ctx, upsertItem,
		arg.Guid,
		arg.Title,
		arg.Description,
		arg.Link,
		arg.Author,
		arg.Pubdate,
		arg.Read,
		arg.Starred,
	)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Feedid,
		&i.Guid,
		&i.Title,
		&i.Description,
		&i.Link,
		&i.Author,
		&i.Pubdate,
		&i.Read,
		&i.Starred,
	)
	return i, err
}
