// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"
)

type DefaultItem struct {
}

type Enclosure struct {
	ID       int64
	Itemid   int64
	Mimetype string
	Url      string
}

type Feed struct {
	ID           int64
	Title        string
	Description  string
	Link         string
	FetchFrom    string
	Language     sql.NullString
	Ttl          int64
	Etag         sql.NullString
	Lastmodified time.Time
}

type Item struct {
	ID          int64
	Feedid      int64
	Guid        string
	Title       sql.NullString
	Description sql.NullString
	Link        sql.NullString
	Author      sql.NullString
	Pubdate     time.Time
	Read        sql.NullInt64
	Starred     sql.NullInt64
}
